archlinux/arch-security-tracker

- .travis.yml
- README.md
- app/__init__.py
- requirements.txt
Add Content Security Policy support using flask-talisman. By default
the force https and session_cookie_secure (forces cookies to be send over https)
options are enabled which break a normal `python run.py` on a local
machine, therefore they have been disabled.
CSP exceptions have been made for style, fonts served from external
source i.e. gooogle and form-action has been set as it's required for
form submission.
> Add basic CSP support

- app/model/package.py
- app/templates/package.html
- app/view/show.py
If there are version information available, use the first version
to create a direct archweb package link instead of using the
archweb search view.
> ui: switch package link from archweb query to direct

- app/templates/form/cve.html
- app/view/add.py
- test/test_cve.py
If the CVE entry already exists, try to merge as much as possible
and warn about all unmerged fields.
This helps to edit issues when they are already added but not noticed.
> cve: add tries to merge with existing entry

- app/view/error.py
The default 404 not-found description looks overly long and boring.
Lets just omit it when we find it, otherwise use the passed e param.
> ui: omit default 404 description

- app/form/cve.py
- app/static/style.css
- app/view/edit.py
The CVE id field cannot be changed while editing. Therefor we mark
the field as readonly and visually display it.
> ui: disable CVE id field in edit mode

- app/templates/cve.html
- app/templates/form/group.html
- app/templates/group.html
- app/view/__init__.py
- app/view/copy.py
- test/test_cve.py
- test/test_group.py
This aids to copy certain entries for faster creation. The most
obvious use case is to copy an AVG from a non lib32 variant into
a lib32 variant without the hassle to fill in everything field
by field via copy-paste.
> copy: allow AVG and CVE entries to be copied into the add form

- app/templates/base.html
- app/view/show.py
add pkgnames the AVG and CVE view
examples:
``` 
AVG-4 - python-flask-something python2-flask-something - Arch Linux
AVG-123 - wireshark - Arch Linux
CVE-1234-1111 - bash zsh fish - Arch Linux
CVE-1234-2222 - bash - Arch Linux
CVE-1234-3333 - Arch Linux
```
When we add additional info to the title it actually becomes overly
long. We drop the tracker part of it has it doesn't add too much
information compared to which packages it they affect.
> add pkgnames to title for the AVG and CVE view

- app/templates/stats.html
The last row of the Types table in the stats.html template appeared to be missing the 'Local' and 'Remote' types for the last row containing totals of the values in the table. I'm not sure if this was intentional or not.
> Added missing td elements

- .travis.yml
- README.md
- update
pyalpm 0.8.2 provides package.base which is the pkgbase of a package so
expac is not a required depdendency anymore.
I'm not 100% sure if this works as intended! @anthraxx please check :)
> Use pyalpm's pkgbase

- app/templates/group.html
- app/view/show.py
- test/test_cve.py
- test/test_group.py
This also fixes a visual issue for staff that displays a delete button
but it can't be used as deletion is forbidden when any advisories
exist referencing the AVG or CVE.
> ui: don't show scheduled advisories for guests in AVG/CVE view

- test/test_advisory.py
- tracker/view/edit.py
Change the advisory issue type accordingly when adding or removing
CVE entries from a group that has already scheduled multiple advisories
because its multi package.
The issue was a missing group-by on the pkgname which resulted in only
selecting one of the multiple advisories that got scheduled and the
others kept its old advisory issue types when it should have been
changed.
This fixes #100
> advosry: fix change type accordingly if the group issues change

- test/test_advisory.py
- test/test_cve.py
- tracker/advisory.py
- tracker/templates/cve.html
- tracker/view/blueprint.py
> view: overwrite urlize filter that populates CVE and AVG links

- tracker/templates/cve.html
cve.circl.lu is hosted by the CERT of luxembourg.
They provide a full JSON API for receiving CVEs from multiple feeds
like:
* NIST National Vulnerability Database
* Common Platform Enumeration (CPE)
* Common Weakness Enumeration (CWE)
* CIRCL incident statistics and threat ranking
* toolswatch/vFeed
> cve: added cve.circl.lu to our cve link collection

- test/test_advisory.py
- tracker/advisory.py
- tracker/model/cve.py
- tracker/templates/advisory.txt
- tracker/util.py
- tracker/view/edit.py
- tracker/view/show.py
Multiple CVEs with varying length make advisory CVE header section
unaligned. Split the issues into columns and rows and align each
column individually to be nicely unter each other.
Fixes #94
> advisory: align varying length issue listing nicely

- CONTRIBUTING.md
- README.md
Include a CONTRIBUTING.md file which is copied from the wiki into it's
own file and include a link to the contributin file in the README.md.
> readme: add link to contributing.md

- config.py
- config/00-default.conf
- tracker/__init__.py
Currently we set two HSTS headers. One in `flask-talisman` and one in
our nginx configuration. This is bad, mhhhhkaaaaay. So let's disable our
hsts header in `flask-talisman` and let's nginx do its job. This closes #150 
Signed-off-by: Christian Rebischke <chris@nullday.de>
> disabled hsts header

- requirements.txt
There doesn't seem to be a pyalpm 0.8.5 on the git.archlinux.org
repository. This is because the pyalpm develoment moved to github, and
releases are now published on pypi. Change the requirements.txt file to
use the pypi version of pyalpm.
> requirements: move pyalpm to pypi version

- tracker/__init__.py
We use not the default parameter list in talisman.init_app(..)
therefore we need to ensure, that we pass the hsts parameter in the
init_app() scope, otherwise it gets overwritten by the hidden
default parameters in init_app().
Signed-off-by: Christian Rebischke <chris@nullday.de>
> Fix position of hsts parameter for flask-talisman

- tracker/cli/db.py
If a new database is initialized the alembic meta data is not
automatically stamped to the latest head. This leads to issues when
trying to create migration scripts. As a fix we automatically stamp the
alembic meta data to the current migration scripts head if the database
did not exist before.
This however does not automatically fix existing databases that lack the
alembic meta data stamp. Those should only affect some dev systems and
instead of carrying around some patch paths, we expect devs to simply
call ./trackerctl db stamp head
Fixes #182
> fix(db): automatically stamp the alembic migrate on db init

- .isort.cfg
Since 5.0.0 the `not_skip` configuration option changed so it's no
longer the same as `--dont-skip`, secondly isort no longer skips
__init__.py by default.
> Drop not_skip option from isort configuration

- migrations/env.py
- tracker/form/admin.py
- tracker/form/group.py
- tracker/form/login.py
- tracker/form/user.py
WTForms now accepts keyword arguments in validate() since 1.1.0
See https://github.com/wtforms/flask-wtf/issues/547 https://github.com/inveniosoftware/flask-security-fork/issues/51
> tracker: accept kwargs in Forms

- README.md
Fix missing 't' in the README.md file.
> Fix typo, security was missing a 't' in readme.md
